### ISSUE TITLE
Regarding linting and code style

### ISSUE THREAD

**Issue by Racso** [flipperdevices/flipper-application-catalog#135]
Hi!

I'd like to address the topic of code style conventions in catalog apps.

When running the app validator, it will fail your app in the linting step if you use code style conventions that are different to the clang default ones that the linter requires.

For example, the linter will fail if you use

`if (from != to)`

instead of

`if(from != to)`

I understand that following a uniform code style is important in the firmware code. However, given that catalog apps are external to the core project, I believe that apps developers could be allowed to use the coding style they prefer.

So, my question is: are those "default" style conventions mandatory even for external apps that don't modify the firmware code? Or would it be valid to publish an app that follows different style conventions?

I know that the linting step of the validator can be skipped, but obviously that wouldn't help if the app is rejected anyways for failing your internal validation.

Thanks!

**Comment by skotopes** [comment]
We don't enforce code style on 3rd party apps. Only on firmware and official apps.

**Comment by hedger** [comment]
App validator has `--nolint` options that is being used for checks in catalog infrastructure. We used to enforce code style before for all apps, but now it is no longer required.

We'll update the docs to reflect that you are not forced to conform to our code style - however, it is welcome.

**Comment by Racso** [comment]
Thank you both. That's good news.
