### ISSUE TITLE
Catalog permanently stuck in "Dev" mode if you click the "Production Apps" toggle

### ISSUE THREAD

**Issue by ssshake** [flipperdevices/flipper-application-catalog#200]
If you click the "Production Apps" toggle on the website under settings, the catalogChannel value in local storage gets changed from "production" to "dev".

When this happens, the "Production Apps" toggle disappears.

Because of this, the user is forever stuck with the dev catalog with no way to switch it back to production.

The only way to fix this is to manually set the local storage value back to "production" or to clear out local storage completely.

![Image 2023-11-23 at 8 56 PM](https://github.com/flipperdevices/flipper-application-catalog/assets/1675868/00bff096-04de-4ec2-85eb-6b28610f357a)

![Image 2023-11-23 at 8 57 PM](https://github.com/flipperdevices/flipper-application-catalog/assets/1675868/c4e4cca7-5bc7-4b91-90be-74a95bee62e6)

**Comment by doomwastaken** [comment]
Greetings. There is a refactor of a lab going on right now, hopefully today we will receive a new version for testing. And today/next week it will be deployed with  the changes. I will make sure this is a part of the refactor

**Comment by doomwastaken** [comment]
Also we do not have a proper channel to report bugs on the web version, since it was mostly used as internal tool, so I will try and fix that too, will update you once I have additional information

**Comment by doomwastaken** [comment]
Checked with Web team, bug is known and fix is in the refactor

**Comment by doomwastaken** [comment]
Dev catalog had this issue fixed, however there are some more bugs pending. Hopefully we will release it next week to the prod

**Comment by doomwastaken** [comment]
![image](https://github.com/flipperdevices/flipper-application-catalog/assets/72250702/292c8abe-8657-4f35-954f-acb8ec3ddefe)
both dev and production lab is fixed
