### ISSUE TITLE
Unitemp: App requires fixes for new API

### ISSUE THREAD

**Issue by xMasterX** [flipperdevices/flipper-application-catalog#204]
Hello! @quen0n 
Required fixes already made in my apps repo, please take them and update manifest (don't forget to bump app version)
https://github.com/flipperdevices/flipper-application-catalog/blob/main/applications/GPIO/unitemp/manifest.yml

Please take changes to your app from here:
https://github.com/xMasterX/all-the-plugins/tree/dev/base_pack/unitemp

In other case I would like to request transfer target repo in the manifest to my `all-the-plugins` repo

**Comment by quen0n** [comment]
Thank you. Your code allowed me to quickly find the error and fix it
