### ISSUE TITLE
racso_sokoban: App requires fixes for new API

### ISSUE THREAD

**Issue by xMasterX** [flipperdevices/flipper-application-catalog#205]
Hello! @Racso 
Required fixes already made in my apps repo, please take them and update manifest (don't forget to bump app version)
https://github.com/flipperdevices/flipper-application-catalog/blob/main/applications/Games/racso_sokoban/manifest.yml

Please take changes to your app from here:
https://github.com/xMasterX/all-the-plugins/tree/dev/non_catalog_apps/sokoban

In other case I would like to request transfer target repo in the manifest to my `all-the-plugins` repo

**Comment by doomwastaken** [comment]
Apps were updated, closing the issue! Thank you
