### ISSUE TITLE
racso_zero: App requires fixes for new API

### ISSUE THREAD

**Issue by xMasterX** [flipperdevices/flipper-application-catalog#206]
Hello! @Racso 
Required fixes already made in my apps repo, please take them and update manifest (don't forget to bump app version)
https://github.com/flipperdevices/flipper-application-catalog/blob/main/applications/Games/racso_zero/manifest.yml

Please take changes to your app from here:
https://github.com/xMasterX/all-the-plugins/tree/dev/non_catalog_apps/zero

In other case I would like to request transfer target repo in the manifest to my `all-the-plugins` repo

**Comment by Racso** [comment]
Thanks for the help!

I'm currently traveling. As soon as I get back home (next week), I'll update the apps.

**Comment by doomwastaken** [comment]
Apps were updated, closing the issue! Thank you
