### ISSUE TITLE
Add Tool

### ISSUE THREAD

**Issue by justlife4x4** [flipperdevices/flipper-application-catalog#429]
Hii, can you please add this tool `https://github.com/jamisonderek/flipper-zero-tutorials/tree/main/subghz/apps/rolling-flaws` I cant understand how to install it, can you please add this tool in store? It would of really great help

**Comment by skotopes** [comment]
See https://github.com/flipperdevices/flipper-application-catalog/blob/main/documentation/Contributing.md
