### ISSUE TITLE
[Barcode_app] apps_data files are missing

### ISSUE THREAD

**Issue by theblackhole** [flipperdevices/flipper-application-catalog#47]
Hello,

I don't know if the issue is on your side or if it is an issue on @xMasterX side so I will create an issue for both.

Linked issue: https://github.com/xMasterX/all-the-plugins/issues/6

TLDR: it seems like required app_data files are missing when installing apps from the Hub/Catalog 

Details :
I have an issue with the [barcode_app](https://lab.flipper.net/apps/barcode_app) installed with the android app via the Hub/Catalog: when I try to load a Code 128 barcode, it says "Missing encoding table".
After reading the [installation instructions on the original github repository](https://github.com/Kingal1337/flipper-barcode-generator#installing) I found that it needs encoding table files in a `apps_data/barcode_data` folder.
This folder is missing on my Flipper Zero:
![image](https://github.com/xMasterX/all-the-plugins/assets/7818904/201283b2-b1d9-4a79-8839-e3ab51cc99c7)
The issue disappeared after I added the missing folder and files manually:
![image](https://github.com/xMasterX/all-the-plugins/assets/7818904/dbc8c9ac-14d4-4e8d-912a-6c8e46542077)

**Comment by hedger** [comment]
Hello!

A fix for resource embedding is coming in next release - https://github.com/flipperdevices/flipperzero-firmware/pull/2901. Then it'll be possible to accept the app in the catalog.
