### ISSUE TITLE
50 app install limit in catalog

### ISSUE THREAD

**Issue by lolroger** [flipperdevices/flipper-application-catalog#85]
It appears that the application catalog will only register a maximum of 50 apps installed on the flipper at one time. After that 50 app threshold is reached, the "installed" status will not persist for any additional apps that get installed and the orange install button will still be available for selection. However, the additional apps in question will be available in the application menu of the flipper itself even if they are not appearing as "installed" on the app catalog.

**Comment by hedger** [comment]
Which app are you using, iOS or Android?

**Comment by hedger** [comment]
From mobile app development team - they said a fix for your issue in coming to app stores later this week.

**Comment by lolroger** [comment]
> Which app are you using, iOS or Android?

I am using the android app.

**Comment by LionZXY** [comment]
Already fixed in dev and on its way to release (on review on Google Play) 🎉

https://github.com/flipperdevices/Flipper-Android-App/releases/tag/1.6.1.1131
