### ISSUE TITLE
Enhancement: Catalog HTML front-end

### ISSUE THREAD

**Issue by MichaelGrafnetter** [flipperdevices/flipper-application-catalog#87]
Hello, I wonder if at least a simple HTML front-end with application list could be generated for the catalog. It could then be served to web browsers instead of the dummy JSON document:
![image](https://github.com/flipperdevices/flipper-application-catalog/assets/8986376/e117e3b1-10c8-4c52-ac84-fcc0e30ea8fc)

**Comment by anfractuosity** [comment]
I came across that page too, you can see the apps at - https://lab.flipper.net/apps though

**Comment by MichaelGrafnetter** [comment]
Thanks @anfractuosity, that's exactly what I was looking for. Is it official, though? Maybe a link could be added to the [ReadMe.md](https://github.com/flipperdevices/flipper-application-catalog/blob/9e9fbb2b4cacb829f68c308fae64b44e25fd1eee/ReadMe.md) to make the catalog easier to find.

I understand that the catalog is a hot new feature and that is why the [catalog.flipperzero.one](https://catalog.flipperzero.one) page does not contain any meaningful info yet. I could imagine it to contain the app list or API doc.

**Comment by anfractuosity** [comment]
I think it is official, as I found https://github.com/flipperdevices/lab.flipper.net
