### ISSUE TITLE
Markdown links are not rendered correctly

### ISSUE THREAD

**Issue by akopachov** [flipperdevices/flipper-application-catalog#95]
According to manifest file explanation given [here](https://github.com/flipperdevices/flipper-application-catalog/blob/main/documentation/Manifest.md#markdown-support) subset of markdown syntax is supported, including "links". However links are not getting rendered correctly on app details page.

![image](https://github.com/flipperdevices/flipper-application-catalog/assets/1217426/135e067d-246b-453c-8da6-76678eb52639)

**Comment by hedger** [comment]
Where does that screenshot come from?

**Comment by akopachov** [comment]
I took that screenshot here https://lab.flipper.net/apps/totp

**Comment by hedger** [comment]
Web part of the catalog is still work-in-progress and hasn't been released yet.

**Comment by CookiePLMonster** [comment]
@hedger Is this still the case currently? At this moment, links still don't display correctly in the web version of the catalog, yet the current ReadMe of this repository does not mention that the website is WIP.
